var table=[{
	name:'新增一个城市',
	id:'0',
	type:'add',
	father:null
},{
  name:'北京',
  id:'1',
  type:'city',
  father:null,
  children:[{
    name:'新增一个部门',
    id:'1-0',
    type:'add',
    father:'1'
  },{
    name:'产品',
    id:'1-1',
    type:'department',
    father:'1',
    children:[{
      name:'新增一个岗位',
      id:'1-1-0',
      type:'add',
      father:'1-1'
    },{
      name:'移动应用开发产品总监',
      id:'1-1-1',
      type:'title',
      father:'1-1',
      children:[{
        name:'招聘要求',
        id:'1-1-1-0',
        type:'yaoqiu',
        father:'1-1-1',
        children:[
          {
            name:'添加一条描述',
            id:'1-1-1-0-0',
            type:'add',
            father:'1-1-1-0'
          },
          {
            name:'具有理科或者工科的本科学位。',
            id:'1-1-1-0-1',
            type:'expression',
            father:'1-1-1-0'
          },
          {
            name:'具有在移动应用产品管理发5年以上的经验，熟悉并且能够管理产品的整个生命周期，包括定义、开发、测试、发布、支持和退市。熟悉互联网业态，特别是对社交类APP的产品设计及用户行为有深刻理解和独到见解。',
            id:'1-1-1-0-1',
            type:'expression',
            father:'1-1-1-0'
          },
          {
            name:'有过成功的APP案例。',
            id:'1-1-1-0-1',
            type:'expression',
            father:'1-1-1-0'
          },
          {
            name:'具有3年以上的项目管理经验。',
            id:'1-1-1-0-1',
            type:'expression',
            father:'1-1-1-0'
          },
          {
            name:'具备明锐的商业头脑和嗅觉以及深厚的分析能力，对数据敏感。',
            id:'1-1-1-0-1',
            type:'expression',
            father:'1-1-1-0'
          },
          {
            name:'具备良好的沟通技巧、领导才能和团队精神。',
            id:'1-1-1-0-1',
            type:'expression',
            father:'1-1-1-0'
          },
          {
            name:'注重细节，富有想象力和创造力，注重结果。',
            id:'1-1-1-0-1',
            type:'expression',
            father:'1-1-1-0'
          },
          {
            name:'注重细节，富有想象力和创造力，注重结果。抗压能力强，能够在一个快节奏的创业环境中游刃有余。',
            id:'1-1-1-0-1',
            type:'expression',
            father:'1-1-1-0'
          },
          {
            name:'熟练使用办公软件和项目管理软件。',
            id:'1-1-1-0-1',
            type:'expression',
            father:'1-1-1-0'
          }
        ]
      },{
        name:'岗位描述',
        id:'1-1-1-1',
        type:'miaoshu',
        father:'1-1-1',
        children:[
          {
            name:'添加一条描述',
            id:'1-1-1-1-0',
            type:'add',
            father:'1-1-1-1'
          },
          {
            name:'根据公司业务战略制订移动端APP产品战略，并负责产品战略的实施。',
            id:'1-1-1-1-1',
            type:'expression',
            father:'1-1-1-1'
          },
          {
            name:'进行市场和竞争对手分析，了解市场和竞争对手动态，定义合适产品来满足用户需求。负责产品的整体规划、设计和产品生命周期管理（从概念提出到产品上线）',
            id:'1-1-1-1-1',
            type:'expression',
            father:'1-1-1-1'
          },
          {
            name:'向公司高层推荐产品计划并获得批准，撰写文档说明产品的要求和项目的路线图，定义项目成功的衡量标准，并且成立项目小组，领导、推动项目按时优质完成。',
            id:'1-1-1-1-1',
            type:'expression',
            father:'1-1-1-1'
          },
          {
            name:'收集用户反馈，进行数据分析，给出产品功能改进意见，提高产品的用户体验。时刻关注产品相关信息，拓展产品功能并提出新的产品创意。',
            id:'1-1-1-1-1',
            type:'expression',
            father:'1-1-1-1'
          },
          {
            name:'紧跟国内外互联网和业内的最新动态，把最先进理念引入到产品设计中。',
            id:'1-1-1-1-1',
            type:'expression',
            father:'1-1-1-1'
          }
        ]
      }]
    },{
      name:'广告系统产品经理',
      id:'1-1-2',
      type:'title',
      father:'1-1',
      children:[{
        name:'任职资格',
        id:'1-1-2-0',
        type:'yaoqiu',
        father:'1-1-2',
        children:[
          {
            name:'添加一条描述',
            id:'1-1-2-0-0',
            type:'add',
            father:'1-1-2-0'
          },
          {
            name:'大学本科及以上学历，计算机相关专业，2年以上互联网广告产品经理工作经验；',
            id:'1-1-2-0-0',
            type:'expression',
            father:'1-1-2-0'
          },
          {
            name:'大学本科及以上学历，计算机相关专业，2年以上互联网广告产品经理工作经验；熟悉互联网的发展、常规网络技术、以及互联网广告所需的技术架构；',
            id:'1-1-2-0-0',
            type:'expression',
            father:'1-1-2-0'
          },
          {
            name:' 熟练使用各种网络产品设计软件，具备较强的项目管理、数据统计分析、用户需求分析、产品流程规划、项目提案和实施能力；',
            id:'1-1-2-0-0',
            type:'expression',
            father:'1-1-2-0'
          },
          {
            name:'工作态度积极主动、良好的沟通协调能力、执行能力、学习能力和团队合作精神，高度的责任心和敬业精神。',
            id:'1-1-2-0-0',
            type:'expression',
            father:'1-1-2-0'
          }
        ]
      },{
        name:'职位描述',
        id:'1-1-2-1',
        type:'miaoshu',
        father:'1-1-2',
        children:[{
            name:'添加一条描述',
            id:'1-1-2-1-0',
            type:'add',
            father:'1-1-2-1'
          },
          {
            name:'负责一猫汽车网平台的互联网广告系统和广告产品的需求分析、产品设计；',
            id:'1-1-2-1-1',
            type:'expression',
            father:'1-1-2-1'
          },
          {
            name:'不断挖掘广告资源，统一规划广告形式和盈利模式，积极推进，满足对外销售和内部推广的需求；',
            id:'1-1-2-1-1',
            type:'expression',
            father:'1-1-2-1'
          },
          {
            name:'根据市场反馈，整理广告系统和产品开发需求，协调相关的研发、测试、运营等部门进行开发实施，保证项目按时完成；',
            id:'1-1-2-1-1',
            type:'expression',
            father:'1-1-2-1'
          },
          {
            name:'制定广告系统的内部使用流程，对各个需求方进行培训。',
            id:'1-1-2-1-1',
            type:'expression',
            father:'1-1-2-1'
          }]

      }]
    },{
      name:'产品经理(商城类)',
      id:'1-1-3',
      type:'title',
      father:'1-1',
      children:[{
        name:'任职资格',
        id:'1-1-3-0',
        type:'yaoqiu',
        father:'1-1-3',
        children:[
          {
            name:'添加一条描述',
            id:'1-1-3-0-0',
            type:'add',
            father:'1-1-3-0'
          },
          {
            name:'国家统招大学本科或以上学历；',
            id:'1-1-3-0-0',
            type:'expression',
            father:'1-1-3-0'
          },
          {
            name:'4年以上工作经验，1年互联网产品策划工作经验，有过大中型互联网站产品经验者优先；1年以上团队管理经验',
            id:'1-1-3-0-0',
            type:'expression',
            father:'1-1-3-0'
          },
          {
            name:'能熟练使用Visio或Axure',
            id:'1-1-3-0-0',
            type:'expression',
            father:'1-1-3-0'
          },
          {
            name:'逻辑思维能力强，做事有条理，具备较强的分析问题和解决问题的能力，擅长沟通表达；',
            id:'1-1-3-0-0',
            type:'expression',
            father:'1-1-3-0'
          },
          {
            name:'思维敏捷，性格开朗，责任感强，工作积极主动，具备学习意识，有良好的团队协作意识；',
            id:'1-1-3-0-0',
            type:'expression',
            father:'1-1-3-0'
          }]

      },{
        name:'职位描述',
        id:'1-1-3-1',
        type:'yaoqiu',
        father:'1-1-3',
        children:[
          {
            name:'添加一条描述',
            id:'1-1-3-1-0',
            type:'add',
            father:'1-1-3-1'
          },
          {
            name:'负责商城产品的功能规划；',
            id:'1-1-3-1-0',
            type:'expression',
            father:'1-1-3-1'
          },
          {
            name:'保障项目及时、优质的上线，涉及设计、开发、测试、验收、培训等各个环节；',
            id:'1-1-3-1-0',
            type:'expression',
            father:'1-1-3-1'
          },
          {
            name:'关注本产品线日常运营问题，并敦促改正或者产品优化；',
            id:'1-1-3-1-0',
            type:'expression',
            father:'1-1-3-1'
          },
          {
            name:'关注行业竞争对手，定期分析竞争对手功能，提出完善本产品线的方案并实施；',
            id:'1-1-3-1-0',
            type:'expression',
            father:'1-1-3-1'
          },
          {
            name:'配合其他产品线完成业务规划。',
            id:'1-1-3-1-0',
            type:'expression',
            father:'1-1-3-1'
          },
          {
            name:'跟相关业务部门沟通、发掘潜在或者现有需求，使其产品化，以支持业务长久发展需要。',
            id:'1-1-3-1-0',
            type:'expression',
            father:'1-1-3-1'
          }]

      }]
    }]
  }]  
},{
  name:'上海',
  id:'2',
  type:'city',
  father:null,
  children:[{
    name:'新增一个部门',
    id:'2-0',
    type:'add',
    father:'2'
  },{
    name:'产品',
    id:'2-1',
    type:'department',
    father:'2',
    children:[{
      name:'新增一个岗位',
      id:'2-1-0',
      type:'add',
      father:'2-1'
    },{
      name:'移动应用开发产品总监',
      id:'2-1-1',
      type:'title',
      father:'2-1',
      children:[{
        name:'招聘要求',
        id:'2-1-1-0',
        type:'yaoqiu',
        father:'2-1-1',
        children:[
          {
            name:'添加一条描述',
            id:'2-1-1-0-0',
            type:'add',
            father:'2-1-1-0'
          },
          {
            name:'具有理科或者工科的本科学位。',
            id:'2-1-1-0-1',
            type:'expression',
            father:'2-1-1-0'
          },
          {
            name:'具有在移动应用产品管理发5年以上的经验，熟悉并且能够管理产品的整个生命周期，包括定义、开发、测试、发布、支持和退市。熟悉互联网业态，特别是对社交类APP的产品设计及用户行为有深刻理解和独到见解。',
            id:'2-1-1-0-1',
            type:'expression',
            father:'2-1-1-0'
          },
          {
            name:'有过成功的APP案例。',
            id:'2-1-1-0-1',
            type:'expression',
            father:'2-1-1-0'
          },
          {
            name:'具有3年以上的项目管理经验。',
            id:'2-1-1-0-1',
            type:'expression',
            father:'2-1-1-0'
          },
          {
            name:'具备明锐的商业头脑和嗅觉以及深厚的分析能力，对数据敏感。',
            id:'2-1-1-0-1',
            type:'expression',
            father:'2-1-1-0'
          },
          {
            name:'具备良好的沟通技巧、领导才能和团队精神。',
            id:'2-1-1-0-1',
            type:'expression',
            father:'2-1-1-0'
          },
          {
            name:'注重细节，富有想象力和创造力，注重结果。',
            id:'2-1-1-0-1',
            type:'expression',
            father:'2-1-1-0'
          },
          {
            name:'注重细节，富有想象力和创造力，注重结果。抗压能力强，能够在一个快节奏的创业环境中游刃有余。',
            id:'2-1-1-0-1',
            type:'expression',
            father:'2-1-1-0'
          },
          {
            name:'熟练使用办公软件和项目管理软件。',
            id:'2-1-1-0-1',
            type:'expression',
            father:'2-1-1-0'
          }
        ]
      },{
        name:'岗位描述',
        id:'2-1-1-1',
        type:'miaoshu',
        father:'2-1-1',
        children:[
          {
            name:'添加一条描述',
            id:'2-1-1-1-0',
            type:'add',
            father:'2-1-1-1'
          },
          {
            name:'根据公司业务战略制订移动端APP产品战略，并负责产品战略的实施。',
            id:'2-1-1-1-1',
            type:'expression',
            father:'2-1-1-1'
          },
          {
            name:'进行市场和竞争对手分析，了解市场和竞争对手动态，定义合适产品来满足用户需求。负责产品的整体规划、设计和产品生命周期管理（从概念提出到产品上线）',
            id:'2-1-1-1-1',
            type:'expression',
            father:'2-1-1-1'
          },
          {
            name:'向公司高层推荐产品计划并获得批准，撰写文档说明产品的要求和项目的路线图，定义项目成功的衡量标准，并且成立项目小组，领导、推动项目按时优质完成。',
            id:'2-1-1-1-1',
            type:'expression',
            father:'2-1-1-1'
          },
          {
            name:'收集用户反馈，进行数据分析，给出产品功能改进意见，提高产品的用户体验。时刻关注产品相关信息，拓展产品功能并提出新的产品创意。',
            id:'2-1-1-1-1',
            type:'expression',
            father:'2-1-1-1'
          },
          {
            name:'紧跟国内外互联网和业内的最新动态，把最先进理念引入到产品设计中。',
            id:'2-1-1-1-1',
            type:'expression',
            father:'2-1-1-1'
          }
        ]
      }]
    },{
      name:'广告系统产品经理',
      id:'2-1-2',
      type:'title',
      father:'2-1',
      children:[{
        name:'任职资格',
        id:'2-1-2-0',
        type:'yaoqiu',
        father:'2-1-2',
        children:[
          {
            name:'添加一条描述',
            id:'2-1-2-0-0',
            type:'add',
            father:'2-1-2-0'
          },
          {
            name:'大学本科及以上学历，计算机相关专业，2年以上互联网广告产品经理工作经验；',
            id:'2-1-2-0-0',
            type:'expression',
            father:'2-1-2-0'
          },
          {
            name:'大学本科及以上学历，计算机相关专业，2年以上互联网广告产品经理工作经验；熟悉互联网的发展、常规网络技术、以及互联网广告所需的技术架构；',
            id:'2-1-2-0-0',
            type:'expression',
            father:'2-1-2-0'
          },
          {
            name:' 熟练使用各种网络产品设计软件，具备较强的项目管理、数据统计分析、用户需求分析、产品流程规划、项目提案和实施能力；',
            id:'2-1-2-0-0',
            type:'expression',
            father:'2-1-2-0'
          },
          {
            name:'工作态度积极主动、良好的沟通协调能力、执行能力、学习能力和团队合作精神，高度的责任心和敬业精神。',
            id:'2-1-2-0-0',
            type:'expression',
            father:'2-1-2-0'
          }
        ]
      },{
        name:'职位描述',
        id:'2-1-2-1',
        type:'miaoshu',
        father:'2-1-2',
        children:[{
            name:'添加一条描述',
            id:'2-1-2-1-0',
            type:'add',
            father:'2-1-2-1'
          },
          {
            name:'负责一猫汽车网平台的互联网广告系统和广告产品的需求分析、产品设计；',
            id:'2-1-2-1-1',
            type:'expression',
            father:'2-1-2-1'
          },
          {
            name:'不断挖掘广告资源，统一规划广告形式和盈利模式，积极推进，满足对外销售和内部推广的需求；',
            id:'2-1-2-1-1',
            type:'expression',
            father:'2-1-2-1'
          },
          {
            name:'根据市场反馈，整理广告系统和产品开发需求，协调相关的研发、测试、运营等部门进行开发实施，保证项目按时完成；',
            id:'2-1-2-1-1',
            type:'expression',
            father:'2-1-2-1'
          },
          {
            name:'制定广告系统的内部使用流程，对各个需求方进行培训。',
            id:'2-1-2-1-1',
            type:'expression',
            father:'2-1-2-1'
          }]

      }]
    },{
      name:'产品经理(商城类)',
      id:'2-1-3',
      type:'title',
      father:'2-1',
      children:[{
        name:'任职资格',
        id:'2-1-3-0',
        type:'yaoqiu',
        father:'2-1-3',
        children:[
          {
            name:'添加一条描述',
            id:'2-1-3-0-0',
            type:'add',
            father:'2-1-3-0'
          },
          {
            name:'国家统招大学本科或以上学历；',
            id:'2-1-3-0-0',
            type:'expression',
            father:'2-1-3-0'
          },
          {
            name:'4年以上工作经验，1年互联网产品策划工作经验，有过大中型互联网站产品经验者优先；1年以上团队管理经验',
            id:'2-1-3-0-0',
            type:'expression',
            father:'2-1-3-0'
          },
          {
            name:'能熟练使用Visio或Axure',
            id:'2-1-3-0-0',
            type:'expression',
            father:'2-1-3-0'
          },
          {
            name:'逻辑思维能力强，做事有条理，具备较强的分析问题和解决问题的能力，擅长沟通表达；',
            id:'2-1-3-0-0',
            type:'expression',
            father:'2-1-3-0'
          },
          {
            name:'思维敏捷，性格开朗，责任感强，工作积极主动，具备学习意识，有良好的团队协作意识；',
            id:'2-1-3-0-0',
            type:'expression',
            father:'2-1-3-0'
          }]

      },{
        name:'职位描述',
        id:'2-1-3-1',
        type:'yaoqiu',
        father:'2-1-3',
        children:[
          {
            name:'添加一条描述',
            id:'2-1-3-1-0',
            type:'add',
            father:'2-1-3-1'
          },
          {
            name:'负责商城产品的功能规划；',
            id:'2-1-3-1-0',
            type:'expression',
            father:'2-1-3-1'
          },
          {
            name:'保障项目及时、优质的上线，涉及设计、开发、测试、验收、培训等各个环节；',
            id:'2-1-3-1-0',
            type:'expression',
            father:'2-1-3-1'
          },
          {
            name:'关注本产品线日常运营问题，并敦促改正或者产品优化；',
            id:'2-1-3-1-0',
            type:'expression',
            father:'2-1-3-1'
          },
          {
            name:'关注行业竞争对手，定期分析竞争对手功能，提出完善本产品线的方案并实施；',
            id:'2-1-3-1-0',
            type:'expression',
            father:'2-1-3-1'
          },
          {
            name:'配合其他产品线完成业务规划。',
            id:'2-1-3-1-0',
            type:'expression',
            father:'2-1-3-1'
          },
          {
            name:'跟相关业务部门沟通、发掘潜在或者现有需求，使其产品化，以支持业务长久发展需要。',
            id:'2-1-3-1-0',
            type:'expression',
            father:'2-1-3-1'
          }]

      }]
    }]
  }]  
}]